### ISSUE TITLE
Tags are not parsed in MatroskaFile.readFile

### ISSUE THREAD

**Issue by hampelratte** [Matroska-Org/jebml#2]
If you parse a file with MatroskaFile.readFile(), the tags of a segment are never parsed, because the if statement checks for the type Tag instead of Tags. Here is a patch:
```
diff --git a/src/main/java/org/ebml/matroska/MatroskaFile.java b/src/main/java/org/ebml/matroska/MatroskaFile.java
index 00682e6..e44f39e 100644
--- a/src/main/java/org/ebml/matroska/MatroskaFile.java
+++ b/src/main/java/org/ebml/matroska/MatroskaFile.java
@@ -146,7 +146,7 @@
           break;
 
         }
-        else if (level1.isType(MatroskaDocTypes.Tag.getType()))
+        else if (level1.isType(MatroskaDocTypes.Tags.getType()))
         {
           parseTags(level1, level2);
 
```

**Comment by mbunkus** [comment]
Thanks. Note that the Java code here is completely unmaintained and, as far as I know, unused. I cannot test your change, but it looks correct, therefore I'm merging it.

If you're interested in doing more maintenance on this code then that would be great. Please send real pull requests in the future and I'll merge them.
